full_rebuild: true
name: "Markdown LaTeX CSS"
description: "Using CSS to make the Markdown to HTML output mimics the Markdown to LaTeX output"
domain: ickc.github.io #If you want to force HTTPS, put down the domain without the http: e.g. example.com
url: https://ickc.github.io #place url
baseurl: /markdown-latex-css #place folder name if site is served in subfolder
permalink: /:title.html
author: #For jekyll-feed
  name: "Kolen"
  email: christian.kolen@gmail.com
  uri: https://ickc.github.io/about/

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "compress"

exclude: [.git, .gitignore, .sass-cache, Gemfile, Gemfile.lock, index.md, README.md, makefile]

gems:
  - jekyll-sitemap

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, p, rt, rp, optgroup, option, caption]
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]
