exclude: [.git, .gitignore, .sass-cache, Gemfile, Gemfile.lock, index.md]

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, p, rt, rp, optgroup, option, caption]
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]